### ISSUE TITLE
’sample_with_class.json‘ file is missing 

### ISSUE THREAD

**Issue by Simon-Stma** [cxa9264/CONFETI#2]
How to generate sample_with_class.json and sample_class_stats.json for Cityscapes dataset when using RCS strategy?

**Comment by cxa9264** [comment]
Hi! Please use following command for data preparation

```shell
python tools/convert_datasets/gta.py data/gta --nproc 8
python tools/convert_datasets/cityscapes.py data/cityscapes --nproc 8
python tools/convert_datasets/synthia.py data/synthia/ --nproc 8
```

Or you can visit [DAFormer](https://github.com/lhoyer/DAFormer#:~:text=Data%20Preprocessing%3A%20Finally%2C%20please%20run%20the%20following%20scripts%20to%20convert%20the%20label%20IDs%20to%20the%20train%20IDs%20and%20to%20generate%20the%20class%20index%20for%20RCS%3A) for more detail.

**Comment by Simon-Stma** [comment]
Thank you very much! Your guidance has been extremely helpful to me :)

**Comment by Simon-Stma** [comment]
Can the code you provided support multi-GPU training? Currently, training once on a single GPU takes about 2 days, and I have four GPUs available. Do you have any suggestions on how to speed up the process?

**Comment by cxa9264** [comment]
The multi-GPU training is not currently supported. You may try mixed precision training for acceleration.

**Comment by Simon-Stma** [comment]
Thanks a lot.
