### ISSUE TITLE
Questions about style transfer models

### ISSUE THREAD

**Issue by Simon-Stma** [cxa9264/CONFETI#4]
Hello, based on my understanding, the first stage of the work primarily focuses on learning the style transfer model, while the second stage involves freezing the weights of the style transfer model and learning the segmentation network from scratch. I'm not sure if this understanding is correct. However, if I understand correctly, the Readme states that the weights of the style model in the first stage are loaded from "latest_net_G." In that case, for the second stage, should you load the weights of the latest style model learned in the first stage from the "cut_checkpoints" folder (the default folder in the source code)?

**Comment by cxa9264** [comment]
Hi! Yes, you should load the CUT model for the second stage (be sure to rename the saved model to 'latest_net_G.pth'). In fact, the provided 'latest_net_G.pth' model is already trained through the first round.

For the first round, the style transfer model can be either randomly initialized or loaded from a pre-trained model. For example, you could train solely with CUT on Cityscapes for a few epochs.

**Comment by Simon-Stma** [comment]
I found that in the first stage, there are three models, G, D, and F. What are the roles of these three models? Because I noticed that only the weights of model G are preserved after the first stage. So, should we also load models D and F (originally latest_net_D and latest_net_F) in the second stage? And according to what you mentioned earlier, should we rename the weights that were preserved as latest_net_G and reload these three models?

**Comment by cxa9264** [comment]
G is the generator and D the discriminator. So in second round, only G.pth is used for style transfer.

**Comment by Simon-Stma** [comment]
Thank you for your direct response. I tested my own dataset and found that in the same number of epochs, the performance of the model in the first stage is higher than in the second stage in terms of mIoU. I have two questions here. Firstly, is this situation caused by my training strategy, possibly due to overfitting in the first stage, which leads to poorer performance when training from scratch in the second stage? Or is it a normal phenomenon because the true performance of my dataset on the model is reflected in the second stage, as the purpose of the second stage is to avoid overfitting in the segmentation model?

**Comment by cxa9264** [comment]
If the difference in mIoU between the two rounds isn't that large, maybe this has something to do with the dataset or hyper-parameters. But if the performance in the second round is significantly worse than the first round, something might be wrong. 

In fact, the results given by the evaluation reflect the performance of the model in both rounds. The purpose of the second round is to train the segmentation model with the more stable stylised input. Normally, the performance in second round should not be worse than the first round.
