### ISSUE TITLE
reg_loss？

### ISSUE THREAD

**Issue by kaigelee** [cxa9264/CONFETI#6]
I want to know the role of reg_loss in contrastive_head.py?

**Comment by cxa9264** [comment]
The reg_loss is a regularization term to avoid trivial prototypes.

**Comment by kaigelee** [comment]
> The reg_loss is a regularization term to avoid trivial prototypes.

Could you please give the source of this loss? For example, the title of the paper or the github link?
Thank you so much!

**Comment by cxa9264** [comment]
Please refer to eq. (13) of this paper [SePiCo](https://arxiv.org/abs/2204.08808).
