### ISSUE TITLE
About epoch_number in style transfer stage

### ISSUE THREAD

**Issue by jetitime** [cxa9264/CONFETI#7]
Hi @cxa9264 ,
  Sorry to distrub you. I found that you set --n_epochs=200, --n_epochs_decay=200, which makes the first stage of the style change take a long time, possibly more than 2 days. I wonder if it necessary to train so long in order to have a good style transfer reslut. 
  Looking forward to your reply. Thank you very much!

**Comment by cxa9264** [comment]
Hello,

In fact, the `n_epochs=200` parameter is not utilized in our code. The style transfer module is trained for the same number of iterations as the segmentation model.

To address the slow training issue, you might consider trying the updated version at https://github.com/cxa9264/CONFETII. This enhanced version eliminates the need for second-stage training and implements automatic mixed-precision training. The training duration is reduced to 40k iterations; however, extending it to 80k iterations could further enhance performance.

Training a DeepLab v2 based model needs ~20 hours and DAFormer based model needs ~26 hours on an A100.

**Comment by jetitime** [comment]
Thank you for your patient reply! I will carefully study Xi the new version you gave.
